/*
 * Copyright (c) since 2021 by PopolonY2k and Leidson Campos A. Ferreira
 * 
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 * claim that you wrote the original software. If you use this software
 * in a product, an acknowledgment in the product documentation would be
 * appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 * misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 */

#include "lua/luatimerapi.h"
#include "lua/luaengineutil.h"
#include <cstdio>


#define __MAX_TIMER_NAME   50


namespace Scarab  {
    namespace Engine  {
        namespace Lua  {

            /**
             * @brief Return the timer name generated by given Id;
             *
             * @param nId The Id that will create the timer name;
             * @return the Timer gnerated string;
             */
            std :: string LuaTimerApi :: GetTimerName( int nId )  {

                char   szRet[__MAX_TIMER_NAME];

                std :: snprintf( szRet, __MAX_TIMER_NAME, "__TIMER_ID_%d", nId );

                return szRet;
            }

            /**
             * @brief Delete global variable declared in Lua or through set_global call.
             *
             * @param pLuaState Lua state to be used by engine call.
             * @param szVarName The variable name that will be removed;
             */
            void LuaTimerApi :: DeleteGlobal( lua_State *pLuaState, const char *szVarName )  {

                lua_pushnil( pLuaState );
                lua_setglobal( pLuaState, szVarName );
            }

            /**
             * @brief Add a timer event handling function that will be triggered
             * to a Lua routine passed by parameter;
             *
             * @param pLuaState Lua state to be used by engine call.
             * @return int number os return data (if any - required by lua engine)
             */
            int LuaTimerApi :: SetTimer( lua_State *pLuaState )  {

                if( lua_gettop( pLuaState ) == 3 )  {

                    lua_getglobal( pLuaState, "timerMapPtr" );

                    TimerMap     *pTimerMap = static_cast<TimerMap *>( lua_touserdata( pLuaState, -1 ) );
                    lua_Unsigned nId        = lua_tointeger( pLuaState, 1 );
                    bool         bExists    = ( pTimerMap -> find( nId ) != pTimerMap -> end() );

                    if( !bExists )  {
                        lua_Unsigned nInterval     = lua_tointeger( pLuaState, 2 );
                        bool         bIsCallBackFn = lua_isfunction( pLuaState, 3 );

                        if( bIsCallBackFn )  {
                            SunLight :: Concurrent :: Timer *pTImer = new SunLight :: Concurrent :: Timer( nId );

                            luaL_ref( pLuaState, LUA_REGISTRYINDEX );
                            lua_setglobal( pLuaState, GetTimerName( nId ).c_str() );

                            pTimerMap -> insert( std :: make_pair( nId, pTImer) );

                            pTImer -> Start( SunLight :: Concurrent :: Timer:: Interval( nInterval ),
                                             [pLuaState](int nId ) {
                                                /*
                                                 * This callback runs on Timer's own
                                                 * background thread - lua_State isn't
                                                 * thread-safe, so this must serialize
                                                 * against every main-thread entry
                                                 * point via the same mutex, or the
                                                 * two threads racing on the
                                                 * interpreter's internal state
                                                 * corrupts it and crashes. try_lock
                                                 * (not lock_guard) is required here:
                                                 * ResetTimer runs reentrantly on the
                                                 * main thread while an outer entry
                                                 * point already holds this mutex, and
                                                 * it calls Timer::Stop(), which joins
                                                 * this very thread. If this callback
                                                 * blocked on the mutex instead of
                                                 * backing off, that join would wait
                                                 * forever on a thread stuck waiting
                                                 * for a lock the joining thread
                                                 * itself holds - a deadlock. Skipping
                                                 * an occasional tick when the main
                                                 * thread is busy is harmless for a
                                                 * game timer.
                                                 */
                                                std :: unique_lock<std :: mutex>  lock( LuaEngineUtil :: s_LuaMutex, std :: try_to_lock );

                                                if( !lock.owns_lock() )
                                                    return;

                                                lua_getglobal( pLuaState, GetTimerName( nId ).c_str() );

                                                if( lua_pcall( pLuaState, 0, 0, 0 ) != 0 )  {
                                                     fprintf( stderr, "Error calling Timer Id [%d] function.\n", nId );
                                                }
                                             }  );
                        }
                        else  {
                            fprintf( stderr, "Invalid callback function parameter.\n" );
                        }
                    }
                    else  {
                        fprintf( stderr, "Timer Id [%llu] already registered.\n", nId );
                    }
                }
                else  {
                    fprintf( stderr, "Invalid number of arguments on SetTimer call.\n" );
                }

                return 0;
            }

            /**
             * @brief Remove a timer previously added by SetTimer;
             *
             * @param pLuaState Lua state to be used by engine call.
             * @return int number os return data (if any - required by lua engine)
             */
            int LuaTimerApi :: ResetTimer( lua_State *pLuaState )  {
                if( lua_gettop( pLuaState ) == 1 )  {
                    lua_getglobal( pLuaState, "timerMapPtr" );

                    TimerMap     *pTimerMap = static_cast<TimerMap *>( lua_touserdata( pLuaState, -1 ) );
                    lua_Unsigned nId        = lua_tointeger( pLuaState, 1 );
                    auto         itItem     = pTimerMap -> find( nId );

                    if( itItem != pTimerMap -> end() )  {
                        DeleteGlobal( pLuaState, GetTimerName( nId ).c_str() );
                        itItem -> second -> Stop();
                        delete itItem -> second;
                        pTimerMap -> erase( itItem );
                    }
                    else  {
                        fprintf( stderr, "Timer Id [%llu] doesn't exist.\n", nId );
                    }
                }
                else  {
                    fprintf( stderr, "Invalid number of arguments on ResetTimer call.\n" );
                }

                return 0;
            }

            /**
             * @brief Register the timer Lua-callable functions.
             */
            void LuaTimerApi :: Register( lua_State *pLuaState )  {

                lua_register( pLuaState, "set_timer", LuaTimerApi :: SetTimer );
                lua_register( pLuaState, "reset_timer", LuaTimerApi :: ResetTimer );
            }
        }
    }
}
